blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Start a discussion
    url: https://github.com/rockmagma02/StreamUtilities/discussions
    about: Please ask and answer questions here if unsure.
